name: C/C++ CI

on:
    push:
        paths:
        - 'ascii85/**'
    pull_request:
        paths:
        - 'ascii85/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install -y build-essential libgtest-dev
    - name: make
      run: make
      working-directory: ascii85
    - name: chmod
      run: chmod +x ./tests
      working-directory: ascii85
    - name: unit_tests
      run: ./tests
      working-directory: ascii85
    - name: random_tests
      run: ./random_tests.sh
      working-directory: ascii85
    - name: clean
      run: make clean
      working-directory: ascii85


