name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install -y build-essential libgtest-dev
    - name: make
      run: |
        cd ascii85
        make
    - name: chmod
      run: |
        cd ascii85
        chmod +x ./run_test
    - name: tests
      run: |
        cd ascii85
        ./run_test
    - name: clean
      run: |
        cd ascii85
        make clean
